### ISSUE TITLE
Use AJAX for saving value

### ISSUE THREAD

**Issue by ernilambar** [carolinan/theme-review#2]
It would be great if AJAX is implemented for saving value. Currently page reloads in every submission.

**Comment by carolinan** [comment]
faked it with 
  jQuery(document).ready(function($) {
      $(".button-primary").click(function(e) {
        e.preventDefault();
          url: location.href;
      });
  });

**Comment by noplanman** [comment]
@carolinan Could you please explain how this change should fake the AJAX behaviour? For me, this just completely disables the functionality of the Save button :confused:

**Comment by carolinan** [comment]
By not reloading the page, and preventing the post data from being sent again on reload. Well that was the intention, on the downside you don't get any notification that your data is saved when you press the button (but it is).

**Comment by noplanman** [comment]
What browser are you using? My changes aren't saved.
Try reloading the page without cache after clicking the Save button.

**Comment by carolinan** [comment]
Yeah you are right, they weren't saved, the db reads a:0:{}

**Comment by noplanman** [comment]
This should be quite easy to implement.
Do you want to do it or shall I?
